---
# - name: connect to play
- hosts: all
  # hosts: "{{ cluster_name }}" #"{{ cluster_name }}"  #user insert cluster name
  gather_facts: no 
  vars_files:
    - vars/access_netapp.yml
  collections:
    - netapp.ontap

  vars:
    input: &input
      hostname: "{{ inventory_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      
  # vars_files:
  # - vars/access_netapp.yml

  tasks:
  
    - name: ping OOB cluster management
      ping:
      connection: local
      register: ping_result

    - import_tasks: 
        - config_alert.yml