---
# - name: connect to play
- hosts: all
  # hosts: "{{ cluster_name }}" #"{{ cluster_name }}"  #user insert cluster name
  gather_facts: no 
  vars_files:
    - vars/access_netapp.yml
  collections:
    - netapp.ontap

  vars:
    input: &input
      hostname: hosts
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      
  # vars_files:
  # - vars/access_netapp.yml

  tasks:
  
  - name: ping OOB cluster management
    ping:
    connection: local
    register: ping_result
    
  - name                  : Enable alert forwarding to Splunk server
    na_ontap_command:
      hostname            : hosts
      username            : "{{ netapp_username }}"
      password            : "{{ netapp_password }}"
      command             : [ 'cluster log-forwarding create -destination hoesplshrpinsv1.na.xom.com -port 4090']
      privilege           : 'admin'
      ontapi              : "32"
      https               : true
      validate_certs: false
    connection: local

  # - include_tasks: roles/config/tasks/config_alert.yml
