---
- name                  : Enable alert forwarding to Splunk server
  na_ontap_command:
    hostname            : "{{ hostname }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'cluster log-forwarding create -destination hoesplshrpinsv1.na.xom.com -port 4090']
    privilege           : 'admin'
    ontapi              : "32"
    https               : true
    validate_certs: false
  connection: local